// ✅ 이건 Project.swift가 아니라 Workspace.swift에 있어야 함!
import ProjectDescription

let workspace = Workspace(
  name: "SeoulMate",
  projects: [
    "App",
    "Features/**",
    "Core/**",
  ],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: false,
    autogeneratedWorkspaceSchemes: .enabled(
      codeCoverageMode: .disabled,
      testingOptions: []
    ),
    renderMarkdownReadme: false
  )
)
